version: '3.9'

networks:
  www-net-dev:
    driver: bridge

services:
  mongo:
    hostname: mongodb-dev
    container_name: mongodb-dev
    image: mongo:latest
    restart: always
    networks:
      - www-net-dev
    volumes:
      - ./docker-volumes/mongodb:/data/db
    ports:
      - 27017:27017
  postgresql:
    hostname: postgres-dev
    container_name: postgres-dev
    image: postgres:15.2
    restart: always
    networks:
      - www-net-dev
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
      - ./scripts/docker-postgresql-multiple-databases/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=order,docs,payment,shipping
    ports:
      - 5432:5432
  pgadmin:
    hostname: pgamdin-dev
    container_name: pgadmin-dev
    image: dpage/pgadmin4:latest
    networks:
      - www-net-dev
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgresql
  frontend:
    hostname: frontend-dev
    container_name: frontend-dev
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    networks:
      - www-net-dev
    volumes:
      - ./frontend:/home/app
    ports:
      - 8000:8000
  account-service:
    hostname: account-service-dev
    container_name: account-service-dev
    build:
      context: ./services/account
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net-dev
    volumes:
      - ./services/account:/home/app
    ports:
      - 3001:3001
  docs-service:
    hostname: docs-service-dev
    container_name: docs-service-dev
    build:
      context: ./services/docs
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net-dev
    volumes:
      - ./services/docs:/home/app
    ports:
      - 3005:3005
    depends_on:
      - postgresql
  order-service:
    hostname: order-service-dev
    container_name: order-service-dev
    build:
      context: ./services/order
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net-dev
    volumes:
      - ./services/order:/home/app
    ports:
      - 3003:3003
    depends_on:
      - postgresql
  payment-service:
    hostname: payment-service-dev
    container_name: payment-service-dev
    build:
      context: ./services/payment
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net-dev
    volumes:
      - ./services/payment:/home/app
    ports:
      - 3004:3004
    depends_on:
      - postgresql
  shipping-service:
    hostname: shipping-service-dev
    container_name: shipping-service-dev
    build:
      context: ./services/shipping
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net-dev
    volumes:
      - ./services/shipping:/home/app
    ports:
      - 3008:3008
    depends_on:
      - postgresql
  catalog-service:
    hostname: catalog-service-dev
    container_name: catalog-service-dev
    build:
      context: ./services/catalog
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net-dev
    volumes:
      - ./services/catalog:/home/app
    ports:
      - 3002:3002
    depends_on:
      - mongo
  chat-service:
    hostname: chat-service-dev
    container_name: chat-service-dev
    build:
      context: ./services/chat
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net-dev
    volumes:
      - ./services/chat:/home/app
    ports:
      - 3007:3007
    depends_on:
      - mongo
  notification-service:
    hostname: notification-service-dev
    container_name: notification-service-dev
    build:
      context: ./services/notification
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net-dev
    volumes:
      - ./services/notification:/home/app
    ports:
      - 3006:3006
    depends_on:
      - mongo
