version: '3.9'

networks:
  www-net:
    driver: bridge

services:
  mongo:
    hostname: mongodb
    container_name: mongodb
    image: mongo
    restart: always
    networks:
      - www-net
    volumes:
      - ./docker-volumes/mongodb:/data/db
    ports:
      - 27017:27017
  postgresql:
    hostname: postgres
    container_name: postgres
    image: postgres:15.2
    restart: always
    networks:
      - www-net
    volumes:
      - ./docker-volumes/postgres:/var/lib/postgresql/data
      - ./scripts/docker-postgresql-multiple-databases/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_MULTIPLE_DATABASES=order,docs,payment,shipping
    ports:
      - 5432:5432
  pgadmin:
    hostname: pgamdin
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    networks:
      - www-net
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 5050:80
    depends_on:
      - postgresql
  keycloak:
    hostname: keycloak
    container_name: keycloak
    image: quay.io/keycloak/keycloak:21.0.1
    ports:
      - 8080:8080
      - 8443:8443
    networks:
      - www-net
    volumes:
      - ./docker-volumes/keycloak/data/import:/opt/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresql:5432/keycloak
      - KC_DB_USERNAME=admin
      - KC_DB_PASSWORD=admin
    depends_on:
      - postgresql
    # TODO: Change to production mode
    command: start-dev --import-realm
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:1.23.3
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/data/static
    networks:
      - www-net
    restart: always
    ports:
      - 3000:80
      - 80:80
    depends_on:
      - account-service
      - docs-service
      - order-service
      - payment-service
      - shipping-service
      - catalog-service
      - chat-service
      - notification-service
  frontend:
    container_name: frontend
    hostname: frontend
    build: ./frontend
    volumes:
      - ./frontend:/home/app
    networks:
      - www-net
    ports:
      - 8000:80
  account-service:
    hostname: account-service
    container_name: account-service
    build:
      context: ./services/account
      dockerfile: Dockerfile
      args:
        - NODE_ENV=production
    environment:
      - NODE_ENV=production
    networks:
      - www-net
    volumes:
      - ./services/account:/home/app
    ports:
      - 3001:3001
  docs-service:
    hostname: docs-service
    container_name: docs-service
    build:
      context: ./services/docs
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net
    volumes:
      - ./services/docs:/home/app
    ports:
      - 3005:3005
    depends_on:
      - postgresql
  order-service:
    hostname: order-service
    container_name: order-service
    build:
      context: ./services/order
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net
    volumes:
      - ./services/order:/home/app
    ports:
      - 3003:3003
    depends_on:
      - postgresql
  payment-service:
    hostname: payment-service
    container_name: payment-service
    build:
      context: ./services/payment
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net
    volumes:
      - ./services/payment:/home/app
    ports:
      - 3004:3004
    depends_on:
      - postgresql
  shipping-service:
    hostname: shipping-service
    container_name: shipping-service
    build:
      context: ./services/shipping
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net
    volumes:
      - ./services/shipping:/home/app
    ports:
      - 3008:3008
    depends_on:
      - postgresql
  catalog-service:
    hostname: catalog-service
    container_name: catalog-service
    build:
      context: ./services/catalog
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net
    volumes:
      - ./services/catalog:/home/app
    ports:
      - 3002:3002
  chat-service:
    hostname: chat-service
    container_name: chat-service
    build:
      context: ./services/chat
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net
    volumes:
      - ./services/chat:/home/app
    ports:
      - 3007:3007
  notification-service:
    hostname: notification-service
    container_name: notification-service
    build:
      context: ./services/notification
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
    networks:
      - www-net
    volumes:
      - ./services/notification:/home/app
    ports:
      - 3006:3006
